#!/usr/bin/env bash
# Generated by deploy/build-hooks.py; edit the generator, then regenerate.
set -Eeuo pipefail
umask 077
die() { printf '[拾记] %s\n' "$*" >&2; exit 1; }
[[ $(uname -s) == Linux && $(id -u) == 0 ]] || die '需要Linux和root。'
[[ ${DEPLOYCTL_APPLICATION:-} == notes ]] || die '需要Notes的ctl上下文。'
image=${DEPLOYCTL_IMAGE:?missing immutable image}
[[ $image =~ ^[a-z0-9][a-z0-9./:_-]*@sha256:[a-f0-9]{64}$ ]] || die '需要固定镜像digest。'
effective="$(dirname -- "${DEPLOYCTL_ENV_FILE:?missing effective snapshot}")/effective.env"
[[ -f $effective && ! -L $effective && $(stat -c %u -- "$effective") == 0 ]] || die '需要ctl生成的私有最终运行配置。'
mode=$(stat -c %a -- "$effective")
(( (8#$mode & 077) == 0 )) || die '最终运行配置必须禁止组和其他用户读取。'
check_log=$(mktemp)
trap 'rm -f -- "$check_log"' EXIT
# ctl has pulled the digest. Go resolves DATABASE_URL or DB_* directly from
# this snapshot, keeping group/project/operator precedence intact.
if ! docker run --rm --pull never --entrypoint shiji --env-file "$effective" "$image" database-check > "$check_log" 2>&1; then
  die '只读数据库预检失败，确认ctl中的DATABASE_URL或DB_HOST/DB_USER/DB_PASSWORD等配置。'
fi
printf '[拾记] ctl有效数据库配置及只读预检通过。\n'
