#!/usr/bin/env bash
# Generated by deploy/build-hooks.py; edit prepare.sh/helpers, then regenerate.
set -Eeuo pipefail
umask 077

# Arguments: private temporary directory, project, environment, database, CLI argv.
# Produces private database.json/target; no remote value is evaluated as shell code.
shiji_read_database() {
  local stage=$1 hub_project=$2 hub_env=$3 database=$4
  shift 4
  "$@" export --project "$hub_project" --env "$hub_env" --format json > "$stage/config.json" || return 1
  jq -e --arg database "$database" --arg project "$hub_project" --arg environment "$hub_env" '
    select(.project == $project and .environment == $environment) | .values as $v |
    {host: ($v.notes_db_address // $v.db_address), port: (($v.notes_db_port // $v.db_port) | tostring),
     user: ($v.notes_db_username // $v.db_username), password: ($v.notes_db_password // $v.db_password),
     database: $database, sslmode: ($v.notes_db_sslmode // "require")} |
    select(.host | type == "string") | select(.host | test("^[A-Za-z0-9:.\\[\\]-]+$")) |
    select(.port | test("^[0-9]{1,5}$")) | select((.port | tonumber) >= 1 and (.port | tonumber) <= 65535) |
    select(.user | type == "string") | select(.user | length > 0) |
    select(.password | type == "string") | select(.password | length > 0) |
    select(.sslmode == "require" or .sslmode == "verify-ca" or .sslmode == "verify-full") |
    (if (.host | contains(":")) and (.host | startswith("[") | not) then "[" + .host + "]" else .host end) as $host |
    . + {uri: ("postgresql://" + (.user | @uri) + ":" + (.password | @uri) + "@" + $host + ":" + .port + "/" + .database + "?sslmode=" + .sslmode + "&connect_timeout=10")}
  ' "$stage/config.json" > "$stage/database.json" 2>/dev/null || return 1
  jq -c '{host, port, user, database}' "$stage/database.json" > "$stage/target"
}

native_die() { printf '[拾记] %s\n' "$*" >&2; exit 1; }
native_plain_path() {
  local path=$1 check=$1
  [[ $path =~ ^/[A-Za-z0-9_./-]+$ && $path != / && $path == "$(realpath -m -- "$path")" ]] || native_die '需要规范的绝对路径，不支持空格或特殊字符。'
  while [[ $check != / ]]; do
    [[ ! -L $check ]] || native_die '原生部署路径不能包含符号链接。'
    check=$(dirname -- "$check")
  done
}
native_private_file() {
  local mode
  [[ -f $1 && ! -L $1 && $(stat -c %u -- "$1") == 0 ]] || native_die '配置必须是 root 拥有的常规文件。'
  mode=$(stat -c %a -- "$1")
  (( (8#$mode & 077) == 0 )) || native_die '配置文件必须禁止组和其他用户读取。'
}
native_root_chain() {
  local check=$1 mode
  while :; do
    if [[ -e $check ]]; then
      [[ -d $check && $(stat -c %u -- "$check") == 0 ]] || native_die '程序/配置目录及祖先必须属于root。'
      mode=$(stat -c %a -- "$check")
      (( (8#$mode & 022) == 0 )) || native_die '程序/配置目录及祖先不能允许组或其他用户写入。'
    fi
    [[ $check != / ]] || break
    check=$(dirname -- "$check")
  done
}
native_meta() {
  local config_dir=$1
  native_plain_path "$config_dir"
  native_private_file "$config_dir/native.json"
  field() { jq -er --arg key "$1" '.[$key] | select(type == "string")' "$config_dir/native.json" 2>/dev/null; }
  domain=$(field domain); port=$(field port); service_user=$(field service_user)
  install_dir=$(field install_dir); data_dir=$(field data_dir)
  hub_url=$(field hub_url); hub_project=$(field hub_project); hub_env=$(field hub_env)
  database=$(field database); cli=$(field cli); token_file=$(field token_file)
  [[ ${#domain} -le 253 && $domain =~ ^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,63}$ ]] || native_die '域名无效。'
  [[ $port =~ ^[0-9]{1,5}$ && $port -ge 1024 && $port -le 65535 ]] || native_die '本机监听端口必须在1024至65535之间。'
  [[ $service_user =~ ^[a-z][a-z0-9-]{1,27}$ ]] || native_die '服务账号标识无效。'
  native_plain_path "$install_dir"; native_plain_path "$data_dir"; native_plain_path "$cli"
  native_root_chain "$install_dir";native_root_chain "$config_dir"
  native_root_chain "$(dirname -- "$cli")"
  [[ $hub_url =~ ^https://[a-zA-Z0-9.-]+(:[0-9]{1,5})?(/[^[:space:]?#]*)?$ && $hub_url != *'@'* ]] || native_die 'ConfigHub地址必须HTTPS。'
  [[ $hub_project =~ ^[a-z0-9][a-z0-9-]{0,62}$ && $hub_env =~ ^[a-z0-9][a-z0-9-]{0,62}$ ]] || native_die 'ConfigHub项目/环境无效。'
  [[ $database =~ ^[a-z][a-z0-9_]{0,62}$ && $database != postgres && $database != template0 && $database != template1 ]] || native_die '需要独立的业务数据库。'
  [[ -x $cli && -f $cli && $(stat -c %u -- "$cli") == 0 ]] || native_die 'ConfigHub CLI必须属于root且可执行。'
  local cli_mode
  cli_mode=$(stat -c %a -- "$cli")
  (( (8#$cli_mode & 022) == 0 )) || native_die 'ConfigHub CLI不能允许组或其他用户写入。'
  CLI=("$cli" --server "$hub_url")
  if [[ -n $token_file ]]; then
    native_plain_path "$token_file"; native_private_file "$token_file"
    CLI+=(--token-file "$token_file")
  fi
}
native_load_env() {
  local config_dir=$1 key value
  native_private_file "$config_dir/service.env"
  while IFS='=' read -r key value; do
    case $key in
      DATABASE_URL|APP_ORIGIN|COOKIE_SECURE|LISTEN_ADDR|WEB_DIR|ATTACHMENTS_DIR|EXPORTS_DIR|NOTE_HISTORY_LIMIT|EXPORT_LIMIT_BYTES|TZ) export "$key=$value";;
      *) native_die '生成配置包含未知字段。';;
    esac
  done < "$config_dir/service.env"
}


[[ ${DEPLOYCTL_APPLICATION:-} == notes ]] || native_die '需要Notes的deployctl上下文。'
environment=${DEPLOYCTL_ENVIRONMENT:?missing deployment environment}
config_dir=${DEPLOYCTL_CONFIG_DIR:?missing deployment config directory}
[[ $config_dir == */notes/"$environment" ]] || native_die '配置目录与部署环境不一致。'
config_root=${config_dir%/notes/"$environment"}
set -- --image "${DEPLOYCTL_IMAGE:?missing immutable image}" \
  --env "$environment" --config-root "$config_root" \
  --domain "${DEPLOYCTL_PARAM_DOMAIN-notes.shier.art}" \
  --config-hub-url "${DEPLOYCTL_PARAM_CONFIG_HUB_URL-https://config.shier.art}" \
  --config-hub-project "${DEPLOYCTL_PARAM_CONFIG_HUB_PROJECT-shier}" \
  --config-hub-env "${DEPLOYCTL_PARAM_CONFIG_HUB_ENV-prod}" \
  --database-name "${DEPLOYCTL_PARAM_DATABASE_NAME-notes}" \
  --cli-binary "${DEPLOYCTL_PARAM_CLI_BINARY-}" \
  --token-file "${DEPLOYCTL_PARAM_TOKEN_FILE-/root/shier-prod.token}"

domain=notes.shier.art image='' environment=prod config_root=/etc/deployctl
hub_url=https://config.shier.art hub_project=shier hub_env=prod database=notes
cli='' token_file='' stage='' lock='' publishing=false
cleanup() {
  # Incomplete publication must restore even when Bash's EXIT status is zero
  # during signal termination. Protect cleanup against repeated TERM/HUP/INT.
  trap '' TERM HUP INT
  if $publishing; then
    for index in "${!destinations[@]}"; do
      if [[ -f $stage/backup-$index ]]; then cp -p -- "$stage/backup-$index" "${destinations[index]}";else rm -f -- "${destinations[index]}";fi
    done
  fi
  if [[ -n $stage ]]; then
    rm -f -- "$stage/config.json" "$stage/database.json" "$stage/target" "$stage/config.env" "$stage/secrets.env" "$stage/metadata" "$stage/saved" "$stage/proposed" "$stage/check.log"
    rm -f -- "$stage/backup-0" "$stage/backup-1" "$stage/backup-2" "$stage/backup-3"
    rmdir -- "$stage"
  fi
  [[ -z $lock ]] || rmdir -- "$lock"
}
trap cleanup EXIT
trap 'exit 143' TERM
trap 'exit 129' HUP
trap 'exit 130' INT
while (($#)); do
  (($#>=2)) || native_die '缺少参数值。'
  case $1 in
    --domain) domain=$2;; --image) image=$2;; --env) environment=$2;; --config-root) config_root=$2;;
    --config-hub-url) hub_url=$2;; --config-hub-project) hub_project=$2;; --config-hub-env) hub_env=$2;;
    --database-name) database=$2;; --cli-binary) cli=$2;; --token-file) token_file=$2;;
    *) native_die "未知参数：$1";;
  esac
  shift 2
done
[[ $(uname -s) == Linux && $(id -u) == 0 ]] || native_die '配置生成需要Linux和root。'
[[ ${#domain} -le 253 && $domain =~ ^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,63}$ ]] || native_die '需要有效HTTPS域名，不带协议。'
domain=${domain,,}
[[ $image =~ ^[a-z0-9][a-z0-9./:_-]*@sha256:[a-f0-9]{64}$ ]] || native_die '需要发布包中的真实镜像digest，不接受浮动tag。'
[[ $environment =~ ^[a-z][a-z0-9-]{0,31}$ && $hub_project =~ ^[a-z0-9][a-z0-9-]{0,62}$ && $hub_env =~ ^[a-z0-9][a-z0-9-]{0,62}$ ]] || native_die '环境或ConfigHub标识无效。'
[[ $hub_url =~ ^https://[a-zA-Z0-9.-]+(:[0-9]{1,5})?(/[^[:space:]?#]*)?$ && $hub_url != *'@'* ]] || native_die 'ConfigHub地址必须HTTPS。'
[[ $database =~ ^[a-z][a-z0-9_]{0,62}$ && $database != postgres && $database != template0 && $database != template1 ]] || native_die '需要独立业务数据库。'
native_plain_path "$config_root";native_root_chain "$config_root"
config_dir="$config_root/notes/$environment"
native_plain_path "$config_dir";native_root_chain "$config_dir"
cli=${cli:-$(command -v confighub || true)}
native_plain_path "$cli";native_root_chain "$(dirname -- "$cli")"
[[ -x $cli && -f $cli && $(stat -c %u -- "$cli") == 0 ]] || native_die '需要root所有的ConfigHub CLI。'
cli_mode=$(stat -c %a -- "$cli");(( (8#$cli_mode & 022) == 0 )) || native_die 'CLI不能允许组/其他用户写入。'
CLI=("$cli" --server "$hub_url")
if [[ -n $token_file ]]; then native_plain_path "$token_file";native_private_file "$token_file";CLI+=(--token-file "$token_file");fi
for tool in docker jq; do command -v "$tool" >/dev/null || native_die "需要$tool。";done
mkdir -p -- "$config_dir";chmod 700 -- "$config_dir"
for file in config.env secrets.env .notes-team.json .database-target; do
  [[ ! -L $config_dir/$file && ( ! -e $config_dir/$file || -f $config_dir/$file ) ]] || native_die '配置目标必须为常规文件。'
done
mkdir -- "$config_dir/.notes-prepare.lock" 2>/dev/null || native_die '另一个配置生成正在运行。'
lock="$config_dir/.notes-prepare.lock"
stage=$(mktemp -d "$config_dir/.notes-prepare.XXXXXX")
if [[ ! -f $config_dir/.notes-team.json && ( -s $config_dir/config.env || -s $config_dir/secrets.env ) ]]; then native_die '已有配置不属于本生成器，未覆盖。';fi
jq -n --arg domain "$domain" --arg project "$hub_project" --arg env "$hub_env" --arg url "$hub_url" --arg db "$database" '{domain:$domain,project:$project,environment:$env,url:$url,database:$db}' > "$stage/metadata"
if [[ -f $config_dir/.notes-team.json ]]; then
  native_private_file "$config_dir/.notes-team.json"
  jq -S . "$config_dir/.notes-team.json" > "$stage/saved";jq -S . "$stage/metadata" > "$stage/proposed"
  cmp -s -- "$stage/saved" "$stage/proposed" || native_die '域名或配置来源变化，拒绝自动切换。'
fi
shiji_read_database "$stage" "$hub_project" "$hub_env" "$database" "${CLI[@]}" || native_die 'ConfigHub读取或字段校验失败，保留原配置。'
if [[ -f $config_dir/.database-target ]]; then cmp -s -- "$config_dir/.database-target" "$stage/target" || native_die '数据库目标变化，拒绝自动切库。';fi
printf 'APP_ORIGIN=https://%s\nCOOKIE_SECURE=true\nLISTEN_ADDR=0.0.0.0:8000\nWEB_DIR=/app/web\nATTACHMENTS_DIR=/data/attachments\nEXPORTS_DIR=/data/exports\nNOTE_HISTORY_LIMIT=200\nEXPORT_LIMIT_BYTES=2147483648\nTZ=UTC\n' "$domain" > "$stage/config.env"
printf 'DATABASE_URL=%s\n' "$(jq -er .uri "$stage/database.json")" > "$stage/secrets.env"
if ! docker run --rm --pull always --entrypoint shiji --env-file "$stage/config.env" --env-file "$stage/secrets.env" "$image" database-check > "$stage/check.log" 2>&1; then
  native_die '镜像拉取或只读数据库预检失败，保留原配置；确认镜像拉取权限和数据库连接。'
fi
chmod 600 -- "$stage/config.env" "$stage/secrets.env" "$stage/metadata" "$stage/target"
destinations=("$config_dir/config.env" "$config_dir/secrets.env" "$config_dir/.database-target" "$config_dir/.notes-team.json")
for index in "${!destinations[@]}"; do [[ ! -f ${destinations[index]} ]] || cp -p -- "${destinations[index]}" "$stage/backup-$index";done
publishing=true
mv -Tf -- "$stage/config.env" "$config_dir/config.env"
mv -Tf -- "$stage/secrets.env" "$config_dir/secrets.env"
mv -Tf -- "$stage/target" "$config_dir/.database-target"
mv -Tf -- "$stage/metadata" "$config_dir/.notes-team.json"
publishing=false
printf '[拾记] ConfigHub配置及数据库预检通过：%s。继续安装或升级。\n' "$config_dir"
