"""Build a self-contained pre hook from the reviewed configuration generator."""
from pathlib import Path
import argparse

ROOT=Path(__file__).resolve().parents[1]
ADAPTER=r'''
[[ ${DEPLOYCTL_APPLICATION:-} == notes ]] || native_die '需要Notes的deployctl上下文。'
environment=${DEPLOYCTL_ENVIRONMENT:?missing deployment environment}
config_dir=${DEPLOYCTL_CONFIG_DIR:?missing deployment config directory}
[[ $config_dir == */notes/"$environment" ]] || native_die '配置目录与部署环境不一致。'
config_root=${config_dir%/notes/"$environment"}
set -- --image "${DEPLOYCTL_IMAGE:?missing immutable image}" \
  --env "$environment" --config-root "$config_root" \
  --domain "${DEPLOYCTL_PARAM_DOMAIN-notes.shier.art}" \
  --config-hub-url "${DEPLOYCTL_PARAM_CONFIG_HUB_URL-https://config.shier.art}" \
  --config-hub-project "${DEPLOYCTL_PARAM_CONFIG_HUB_PROJECT-shier}" \
  --config-hub-env "${DEPLOYCTL_PARAM_CONFIG_HUB_ENV-prod}" \
  --database-name "${DEPLOYCTL_PARAM_DATABASE_NAME-notes}" \
  --cli-binary "${DEPLOYCTL_PARAM_CLI_BINARY-}" \
  --token-file "${DEPLOYCTL_PARAM_TOKEN_FILE-/root/shier-prod.token}"
'''

def generated():
    libraries=[ROOT/'notes-server-go/ops/config-hub-lib.sh',ROOT/'notes-server-go/ops/native/lib.sh']
    result='#!/usr/bin/env bash\n# Generated by deploy/build-hooks.py; edit prepare.sh/helpers, then regenerate.\nset -Eeuo pipefail\numask 077\n'
    for path in libraries:
        result+='\n'+path.read_text(encoding='utf-8').split('\n',1)[1]
    prepare=(ROOT/'deploy/prepare.sh').read_text(encoding='utf-8')
    result+='\n'+ADAPTER+'\n'+prepare[prepare.index('domain=notes.shier.art'):]
    return result.replace('现在可执行deployctl install/upgrade。','继续安装或升级。').encode('utf-8')

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    target=ROOT/'deploy/hooks/pre-install.sh';data=generated()
    if args.check:
        if not target.is_file() or target.read_bytes()!=data:
            raise SystemExit('Stale hook; run python3 deploy/build-hooks.py')
    else:
        target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data)
