import {ArrowLeft,Bot,ChevronRight,FolderArchive,HardDrive,ShieldCheck,Trash2,KeyRound,Plus,Check,LogOut,Copy} from 'lucide-react';
import {useEffect,useState} from 'react';
import {api,type Account,type Token,type ExportOptions,type ExportBundle} from './api';
const READ=['notes:read','folders:read','attachments:read','tags:read'];
const WRITE=[...READ,'notes:create','notes:update','folders:write','attachments:write','tags:write'];
export function Settings({account,onBack,onTrash,onExport,onLogout,notify}:{account:Account;onBack:()=>void;onTrash:()=>void;onExport:(options:ExportOptions)=>Promise<ExportBundle>;onLogout:()=>void;notify:(s:string)=>void}){
 const [page,setPage]=useState<'settings'|'agent'|'token'|'export'>('settings');const [tokens,setTokens]=useState<Token[]>([]);const [name,setName]=useState('');const [scope,setScope]=useState('read');const [allowTrash,setAllowTrash]=useState(false);const [result,setResult]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [includeTrash,setIncludeTrash]=useState(true);const [includeHistory,setIncludeHistory]=useState(true);const [exports,setExports]=useState<ExportBundle[]>([]);
 async function loadExports(){try{setExports((await api.exports()).items)}catch(e){setError((e as Error).message)}}
 async function load(){try{setTokens((await api.tokens()).items);setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(page==='agent')void load();if(page==='export')void loadExports()},[page]);
 return <section className="settings-page"><header><button className="back-button" disabled={busy} onClick={()=>{setResult(null);setError('');if(page==='settings')onBack();else setPage(page==='token'?'agent':'settings')}}><ArrowLeft size={18}/>{page==='settings'?'文件夹':page==='token'?'Agent 接入':'空间设置'}</button><h1>{page==='settings'?'空间设置':page==='agent'?'Agent 接入':page==='export'?'图文导出':'创建 Token'}</h1><p className="header-subtitle">{page==='settings'?'管理账户与访问权限。':page==='agent'?'让 Agent 帮你记录与整理。':page==='export'?'把你的记录和图片一起保存到本地。':'为不同的 Agent 设置独立权限。'}</p></header>
 {error&&<div className="inline-notice" role="alert">{error}</div>}
 {page==='settings'?<><div className="account-card"><span className="avatar">{account.display_name.slice(0,1)}</span><div><strong>{account.display_name}的私人空间</strong><span>{account.email}</span></div><ShieldCheck size={21}/></div><div className="settings-section"><button className="settings-row" onClick={()=>setPage('agent')}><Bot size={21}/><span><strong>Agent 接入</strong><small>Token 管理与连接说明</small></span><ChevronRight size={17}/></button><button className="settings-row" onClick={()=>{setError('');setPage('export')}}><FolderArchive size={21}/><span><strong>导出图文包</strong><small>笔记、图片及可选的历史版本</small></span><ChevronRight size={17}/></button><button className="settings-row" onClick={onTrash}><Trash2 size={21}/><span><strong>回收站</strong><small>找回移除的笔记</small></span><ChevronRight size={17}/></button><button className="settings-row" onClick={onLogout}><LogOut size={21}/><span><strong>退出登录</strong><small>保存后退出当前账户</small></span><ChevronRight size={17}/></button></div><div className="settings-section"><div className="info-heading"><HardDrive size={18}/><strong>数据保存</strong></div><p className="settings-copy">笔记与图片保存在服务器。编辑失败时会在当前浏览器保留草稿。完整备份需要同时备份数据库和图片目录。</p></div><div className="privacy-note"><ShieldCheck size={16}/><p>每位用户拥有独立空间。Agent 只能访问你的 Token 授权的内容。</p></div></>:
 page==='export'?<><div className="export-intro"><FolderArchive size={28}/><h2>完整保存图文记录</h2><p>ZIP 包包含正文、文件夹、标签、引用图片和可离线阅读的页面。打开解压后的 index.html 即可阅读；原始 JSON 一并保留。</p></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onExport({include_trash:includeTrash,include_history:includeHistory});await loadExports()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset className="export-options" disabled={busy}><label className="token-extra-scope"><input type="checkbox" checked={includeTrash} onChange={e=>setIncludeTrash(e.target.checked)}/>包含回收站笔记</label><label className="token-extra-scope"><input type="checkbox" checked={includeHistory} onChange={e=>setIncludeHistory(e.target.checked)}/>包含已保留的历史版本及其图片</label></fieldset><p className="settings-copy">只导出当前账户的数据。历史版本只限仍在保留范围内的记录。此包不包含登录凭证，不能替代服务器整库备份。</p><button className="primary-button full-width" disabled={busy}>{busy?'正在准备图文包…':'生成并下载 ZIP'}</button></form>{busy&&<p className="export-status" role="status">正在整理正文与图片，请保持页面打开。</p>}{exports.length>0&&<div className="recent-exports"><h2>最近导出</h2><p className="settings-copy">准备好的文件保留 15 分钟，可以再次下载。</p>{exports.map(bundle=><div className="recent-export" key={bundle.id}><div><strong>{bundle.ready?`${bundle.counts.notes} 篇笔记 · ${bundle.counts.attachments} 张图片`:'仍在准备中'}</strong><span>{bundle.ready?`${(bundle.size_bytes/1024/1024).toFixed(1)} MiB · `:''}{new Date(bundle.expires_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} 前有效</span></div><button className="text-button" disabled={!bundle.ready||busy} onClick={()=>{if(new Date(bundle.expires_at)<=new Date()){setError('文件已过期，请重新生成。');void loadExports();return}api.downloadExport(bundle);notify('浏览器开始下载图文包。')}}>再次下载</button></div>)}</div>}</>:
 page==='agent'?<><div className="section-toolbar"><span className="section-caption">我的访问凭证</span><button className="primary-button" onClick={()=>{setResult(null);setName('');setScope('read');setAllowTrash(false);setPage('token')}}><Plus size={16}/>创建 Token</button></div>{!tokens.length&&!error&&<p className="settings-copy">还没有访问凭证，创建后即可连接 Agent。</p>}{tokens.map(token=><div className="token-row" key={token.id}><div className="token-title"><KeyRound size={18}/><strong>{token.name}</strong><span className={`status-badge ${token.revoked?'revoked':''}`}>{token.revoked?'已撤销':new Date(token.expires_at)<new Date()?'已过期':'有效'}</span></div><p>{token.scopes.includes('notes:update')?'读取、创建和修改':'只读'} · {new Date(token.expires_at).toLocaleDateString('zh-CN')} 到期</p><button className="text-button danger" disabled={token.revoked||busy} onClick={async()=>{setBusy(true);try{await api.revokeToken(token.id);await load();notify('访问凭证已撤销。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{token.revoked?'访问权限已撤销':'撤销访问'}</button></div>)}<div className="connection-help"><h2>连接你的 Agent</h2><p>API 使用 Bearer Token。将地址和密钥配置在 Agent 的环境变量中。</p><pre>NOTES_API_URL={location.origin}/api/v1<br/>NOTES_API_TOKEN=你的密钥</pre><p>API 与 Skill 包名称为 shiji-notes，安装后即可通过 Markdown 或按块操作笔记。读写模板默认不包含回收站权限，可在创建时单独开启。本地 HTTP 调试需设置 NOTES_ALLOW_LOCAL_HTTP=1。</p></div></>:
 result?<div className="token-success"><span><Check size={26}/></span><h2>访问凭证已创建</h2><p>完整密钥仅显示这一次，请妥善保存。</p><code>{result}</code><button className="secondary-button full-width" onClick={()=>void navigator.clipboard.writeText(result).then(()=>notify('凭证已复制。')).catch(()=>notify('复制失败，请手动选中密钥。'))}><Copy size={16}/>复制密钥</button><button className="primary-button full-width" onClick={()=>{setResult(null);setPage('agent')}}>返回凭证列表</button></div>:
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const token=await api.createToken(name.trim(),scope==='read'?READ:[...WRITE,...(allowTrash?['notes:trash']:[])]);setResult(token.secret)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="form-field">名称<input required maxLength={60} placeholder="例如：我的 Agent" value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-field">访问权限<select value={scope} onChange={e=>setScope(e.target.value)}><option value="read">只读</option><option value="write">读取、创建和修改</option></select></label>{scope==='write'&&<label className="token-extra-scope"><input type="checkbox" checked={allowTrash} onChange={e=>setAllowTrash(e.target.checked)}/>允许移入回收站和恢复笔记</label>}<div className="inline-notice"><ShieldCheck size={17}/>有效期 30 天。可随时撤销访问权限。</div><button className="primary-button full-width" disabled={busy}>{busy?'正在创建…':'创建访问凭证'}</button></form>}
 </section>;
}
